### PR TITLE
fix(jira) Fix retrieval of Jira issue title

### PR DESCRIPTION
**Pull request by chrisse27**
Please remember the [Contributing Guidelines](https://github.com/toggl/track-extension/blob/master/docs/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?

Fixes the retrieval of the Jira issue title

## :bug: Recommendations for testing

All changes should be tested across Chrome and Firefox.

## :memo: Links to relevant issues or information

toggl#2086

### CODE REVIEW

**Comment by chrisse27** [comment]
@nunofmn Is there any chance that someone from the maintainers will look as this PR or does nobody have time currently?

**Comment by nunofmn** [comment]
@chrisse27 thanks for the PR! I will take a look at it soon. 👍

**Review by nunofmn — APPROVED** [review]
LGTM! 👍 🚀

**Comment by chrisse27** [comment]
Thanks @nunofmn! Just one question regarding the version. The master branch has now been updated to 2.0.8 but the latest version that was available on the Chrome store was already 2.0.8. So shouldn't the newest version be 2.0.9?

**Pull request merged**
