### PR TITLE
Adding TFS

### PR DESCRIPTION
**Pull request by ReddwarfCro**
I use Team Foundation Server and i really missed Toggl-button extension, so i extended this extension. I created TFS.js in witch is all code.

### CODE REVIEW

**Comment by IndrekV** [comment]
The permission "*://*/tfs/DefaultCollection/*" requires the user to give permissions to all the pages that user visits. We try to keep the permissions at a minimum. This pull request will not be merged at it's current state.

**Comment by MaximRouiller** [comment]
Was there any follow-up to this feature? Any way to support the online TFS in other ways?

**Comment by IndrekV** [comment]
Since it seems that there is no one url the TFS server is used, there is no way to add it to the extension. Only possible way to use your custom domain TFS server is to create a custom extension based on Toggl Button and this pull request. Here is a guide on how to add custom domains to the extension 
https://github.com/toggl/toggl-button/wiki/Adding-custom-domains

**Comment by ReddwarfCro** [comment]
Now I removed custom TFS installation And leave only  visualstudio online.

**Pull request closed without merging**
