### PR TITLE
fix dropdowns not appearing in JIRA popup issue view

### LINKED ISSUE #1448: Jira Kanban board - can't filter projects or tags
* **OS version**: W10
* **Browser version**: Chrome 75
* **Extension version**: 1.37.4

#### Relevant integration (if any):

JIRA

### 🐛 Describe the bug

When starting a timer in JIRA from the Kanban board, the "Find project" and "Find tags" fields aren't selectable, so you have to scroll through the list to find your project/tag.
image

The field works ok from the Issues page.

### Expected behaviour

The search field should be selectable so you can search for a project or tag.

### Steps to reproduce

1. Log into Jira
2. Open a Kanban board
3. Click on an Issue
4. Click Start timer
5. Open the projects dropdown
6. Click on the search field

### Other details or context

[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3155115/conversations/22433077780)

### LINKED ISSUE #1623: Jira integration: cannot select project from modal view
* **OS version**: Windows 10
* **Browser version**: Chrome 79
* **Extension version**: Version 79.0.3945.79 (Official Build) (64-bit)

### 🐛 Describe the bug

the Project dropdown is no longer clickable when you click "Start Timer". Also the "Start Timer" button appears twice.

### Expected behaviour

There should only be 1 "Start Timer" button and the "Project" dropdown should be clickable.

### Steps to reproduce

1. Enable the Jira integration
2. Go to a board for a sprint
3. Open a Jira story modal view
4. Click "Start Timer" on the Jira story
5. Attempt to set the Project. It won't work.

### Other details or context

It _does_ work if you go to the full page for the Jira story, but not the modal view.

### PR DESCRIPTION
**Pull request by lise-toggl**
## :star2: What does this PR do?

Fixes project and tag dropdowns not working in this issue view:
image

*NOTE*: still need to fix input fields not being usable on the popup (description, project filter, tag filter) (#1448) - not sure what's happening here

## :bug: Recommendations for testing

Start a timer from the JIRA issue popup. ([link to our test board](https://togglbutton.atlassian.net/jira/software/projects/NGSP/boards/3?selectedIssue=NGSP-2))

## :memo: Links to relevant issues or information

Closes #1448 
Closes #1623

### CODE REVIEW

**Comment by lise-toggl** [comment]
edit form inputs work without jira's `focusin`, `focusout` and `blur` events

tried to stop them activating on the description field but doesn't work yet :cry:

**Comment by bryanph** [comment]
Here seems to be a hint: 
image

Whenever that pesky little button receives `blur` event it seems to regain the focus again.

**Comment by tcrammond** [comment]
another possible hint:

If the popup is a descendent of the Jira modal (rather than existing in the root of the page. I dragged it around in the devtools inspector), it all works fine. I doubt we can do something sensible to change where it is rendered for an individual integration, but maybe it can lead us to a fix 🤔

**Comment by lise-toggl** [comment]
@tcrammond thanks! @bryanph and I discussed it more in slack and decided to experiment with using an iframe for the popup instead to completely avoid weird interactions with the underlying page. I've been working on this and confirm using an iframe does at least fix #1622, and when I get the dropdowns working :see_no_evil: it should fix this too :crossed_fingers:

**Comment by lise-toggl** [comment]
@tcrammond you're a hero :hugs:  

I added an option to add the edit popup into a specific container rather than the body, which can be specified when creating the timer links. This also works for #1622 :tada:

**Comment by lise-toggl** [comment]
Added a small change to the next-gen project selector to avoid two buttons being shown when an issue belongs to an epic. This should now also close #1623

**Pull request merged**
