### PR TITLE
Suport to Visual Studio Online

### PR DESCRIPTION
**Pull request by GersonDias**
Suport to Visual Studio Online workitems.

image

### CODE REVIEW

**Comment by Mardaneus86** [comment]
FYI: This does not work with the new task form which is currently in preview on VSO. To make it work with that new layout I have created the following snippet. I know it's not as nice as it should be. It needs some work to make it work for both the new and the old scenario.

```
function createTFSButton(homeElement) {
	var y, link,
		descriptionTitle = "",
		home, titleHolder;

	home = homeElement;
	if (home.innerHTML != "") {
		titleHolder = home.querySelector('.workitemcontrol.work-item-control.work-item-form-title');
		var workItemId = home.querySelector(".workitemcontrol.work-item-control.work-item-form-id a").innerText;
		
		descriptionTitle = titleHolder.querySelector("input").title + " (TFS Workitem ID: " + workItemId + ")";
		
		link = togglbutton.createTimerLink({
			className: 'tfsTogglButton',
			description: descriptionTitle
		});

		var div = createTag('div');
		div.style.float = 'right';
		div.appendChild(link);
		if (home.querySelectorAll('.work-item-form-header-controls-container .toggl-button').length == 0) {
			home.querySelector('.work-item-form-header-controls-container').appendChild(div);
		}
	}

}
```

**Comment by GersonDias** [comment]
Hello, Mardaneus86.

Unfortunately new work item form still in very preview state and probably will change many times until this came alive. Although this, just some vso accounts have the new work item available for tests... 

Anyway, there are a new way to do this kind of functionality in VSO though [Extensions](https://www.visualstudio.com/en-us/integrate/extensions/overview). I'm already working in that and I will release that soon...

**Comment by Mardaneus86** [comment]
Agree that it will probably change often until it is released. 

I'm curious about what you're working on regarding the VSO extensions. Can't really imagine what it would look like with Toggl :smile:

**Comment by GersonDias** [comment]
Some "spoiler" of what will release in a few weeks! :)

image

image

image

image

I will release that as an open source extension for Visual Studio Online. I know that won't have the same usability of chrome extension, but, hey... works on every browser and really integrated with VSO! :)

**Comment by Mardaneus86** [comment]
I like the idea and should work great in a team environment like VSO! Looking forward to it

**Comment by IndrekV** [comment]
I simplified the solution 2a790419f34ae73bd22722cc9a7de6b607150a43 and added VSO integration to Toggl Button.

**Pull request closed without merging**
