### PR TITLE
Add Workfront Integration

### PR DESCRIPTION
**Pull request by gonensh**
This adds the ability to track time on Workfront tasks and issues.
"Start Timer" button shows on the Updates tab of any Issue or Task.

### CODE REVIEW

**Comment by gonensh** [comment]
Hey @IndrekV 
Can you give any input on this PR?
Any chance it will be merged anytime soon?

Thanks!
Gonen

**Comment by IndrekV** [comment]
I tried to create an account for Workfront but it was not very easy. This is why this has taken so long to approve.

**Comment by gonensh** [comment]
@IndrekV, thanks for the quick response.
I can ask my Workfront account manager to expedite things and get a two-week trial.
Would that work?

**Comment by IndrekV** [comment]
Yes, It would only take me a day to test it out.

**Comment by gonensh** [comment]
This PR is obsolete. Please see PR #602.

**Pull request closed without merging**
