### PR TITLE
Office.com calendar Integration

### PR DESCRIPTION
**Pull request by Korri**
Other people meeting preview:
screenshot from 2018-07-05 16-19-28
Other people event details:
screenshot from 2018-07-05 16-19-37
My event preview:
screenshot from 2018-07-05 16-27-26

### CODE REVIEW

**Comment by langri-sha** [comment]
Hi @Korri! It looks like they're changing hostnames to https://outlook.live.com, or at least I'm not able to access it from https://outlook.office.com with my MS Office account.

Could you please take a look?

**Comment by Korri** [comment]
Hey @langri-sha it is https://outlook.office.com  on my side, but I'm using a corporate account. We can add an alias if they both work the same.

**Comment by langri-sha** [comment]
That might be it then! Yes, thanks, if you can add an alias that would help :bowing_man:!

**Comment by Korri** [comment]
Updated

**Comment by langri-sha** [comment]
Yup, this is fine! Everything looks good on the stable Calendar release. 

Thanks a lot :bowing_man:!

**Pull request merged**
