### PR TITLE
Add Workfront support

### PR DESCRIPTION
**Pull request by gonensh**
Hey @IndrekV ,

Here is the Workfront integration adapted to the latest version of Toggl-button.
This replaces PR #559 

Please let me know if you are having trouble getting a trial with Workfront.

Thanks!
Gonen

### CODE REVIEW

**Comment by IndrekV** [comment]
Hi, I haven't managed to get an account with Workfront. They don't create temporary trial accounts and have redirected me to some partnering website that is probably not what I need.

**Comment by gonensh** [comment]
I will try to get you a login to a sandbox in Workfront.

**Comment by gonensh** [comment]
Hi @IndrekV,

I have a Workfront sandbox ready for you to test the Toggl button extension with.
Please provide an email address so I can create an account for you.

Thanks,
Gonen

**Comment by IndrekV** [comment]
@gonensh My email is indrek@toggl.com

**Comment by IndrekV** [comment]
Thank you for your work and for making it possible for me to test the integration. I'll try to release the new version of Toggl Button tomorrow.

**Pull request merged**
