### PR TITLE
Add Taskworld To Supported Apps

### PR DESCRIPTION
**Pull request by cgreid4077**
Add Taskworld to Supported Apps

### CODE REVIEW

**Comment by cgreid4077** [comment]
screen shot 2017-04-17 at 11 06 56 am

**Comment by syko** [comment]
Hi, I can't see the button in Taskworld.
In fact I'm not sure if this PR is complete or still a wip?

**Comment by cgreid4077** [comment]
Don’t worry about it.  Taskworld released their own internal time tracking, so Toggl is no longer necessary.

Chris Reid | Information Systems Specialist II
UAB Medicine | Callahan Eye Hospital & Clinics
205.325.8336 | cgreid@uabmc.edu<mailto:cgreid@uabmc.edu>

uabmedicine.org<http://uabmedicine.org/>
Knowledge that will change your world

**Comment by syko** [comment]
Fair enough

**Pull request closed without merging**
