### PR TITLE
Add Kanbanist integration

### PR DESCRIPTION
**Pull request by cosnomi**
## :star2: What does this PR do?
Add Kanbanist integration.  
Kanbanist is an inofficial tool that adds Kanban-like task management for Todoist. The toggl buttons will appear in each Kanban box just beside the task title when you hover the cursor on Kanban boxes. 

## :bug: Recommendations for testing

All changes should be tested across Chrome and Firefox.

## :memo: Links to relevant issues or information
- https://kanban.ist
- https://github.com/mwakerman/kanbanist/issues/33

### Chrome
image
On hover:
image

### Firefox
image
On hover:
image

### CODE REVIEW

**Comment by cosnomi** [comment]
I added Firefox screenshots. The function worked correctly in Firefox as well as in Chrome.

**Comment by cosnomi** [comment]
Thanks for the review.
Yeah, I agree with your idea. I will work on it.

**Comment by cosnomi** [comment]
@tcrammond
As the pull request that overrides Kanbanist CSS has been merged, the Toggl button is now always shown when a timer is running in both Chrome and Firefox.  
image

**Comment by tcrammond** [comment]
@cosnomi Looks good, thank you 👍 we'll include the integration in a release this week.

**Pull request merged**
