### PR TITLE
Add ManageEngine Support

### PR DESCRIPTION
**Pull request by ydbendasan**
This PR adds support for ServiceDesk by ManageEngine

image

### CODE REVIEW

**Comment by dooart** [comment]
Hey, @ydbendasan! Thank you for the pull request.

I tried to test this but the interface looks completely different than the one in your screenshot. Are you using an older version of an on-premises installation of Service Desk?

**Comment by ydbendasan** [comment]
Hi,

Yes that is possible, which version is the latest one? We upgraded it last year I believe.

I’m aware that we’ll be upgrading it next week to patch for the recent 0-day bugs.

Sent from my mobile device

On 8 Feb 2018, at 20:52, Thiago Duarte <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey, @ydbendasan<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fydbendasan&data=02%7C01%7C%7Cac805801cc25420f479508d56f35dd78%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636537199489448866&sdata=Aru%2F4PN5alMJuFyCebXMraj4qNw%2BAO0kSnfNv0TwYtA%3D&reserved=0>! Thank you for the pull request.

I tried to test this but the interface looks completely different than the one in your screenshot. Are you using an older version of an on-premises installation of Service Desk?

**Comment by dooart** [comment]
This is how it looks like for me:
image

It seems that their new UI has been available [since 2014](https://blogs.manageengine.com/help-desk/servicedesk/2014/11/21/manageengine-unveils-revamped-web-ui-for-servicedesk-plus-on-demand.html), at least for their SaaS version (cloud-hosted by themselves).

**Comment by ydbendasan** [comment]
hmm, it does look very different to what we have. How do you suggest we move forward with this? Essentially I'm trying to add the Toggl Button to the On-Premise version and I'm sure there are other On-Premise installations that would benefit from this version.

**Comment by dooart** [comment]
Our policy has been that in order to support any on-premises installation we also need to support the public version of the tool. You can wait until we (or somebody else) add an integration for the cloud version or you can do it yourself along with this PR.

Also - could you please squash your commits?

**Comment by ydbendasan** [comment]
Thanks dooart, 

I've added the new interface compatibility now, however I'm not quite sure how to squash my commits. I'm quite new to GitHub and git on the command line I'm afraid. Happy to squash if you can point me in the right direction.
I also read that when accepting a pull request, you can tick a box to squash all commits so maybe it is easier that way?

**Comment by dooart** [comment]
Thanks @ydbendasan! We'll review your PR soon. :)

**Comment by ydbendasan** [comment]
Thanks @dooart !!

now that it's merged, when should we expect to see this in the Chrome Web Store?

**Comment by dooart** [comment]
We should release a new version within the next few days. :)

**Comment by dooart** [comment]
Hey, @ydbendasan! ManageEngine integration is now officially available in the latest version (v1.10.3)

**Comment by ydbendasan** [comment]
Hey @dooart , yes I noticed and already installed and using it :)

this is my first open source contribution that has been accepted into a repo!!

Thanks again.

**Pull request merged**
