### PR TITLE
Add Microsoft Planner Integration

### PR DESCRIPTION
**Pull request by clptrsn**
Adds Microsoft Planner Integration, https://tasks.office.com/. Tested on the latest versions of Google Chrome and Microsoft Planner.

The timer button shows up in the icon row for the task cards. 
image

### CODE REVIEW

**Comment by reyo** [comment]
**Please merge this!**

**Comment by clptrsn** [comment]
Updated to resolve the conflicts in the README.md

**Comment by langri-sha** [comment]
Thanks, it's working perfectly!

**Comment by clptrsn** [comment]
I'm sorry, but I just noticed that I didn't update the number next to the Microsoft Planner in the list of Services in the README.md. It didn't show up as a conflict when I updated this branch. It's a simple change on line 62 of README from 117 to 118.

How should I proceed to get this fixed? Thank You

**Comment by langri-sha** [comment]
Don't worry. We're going to clean up the README so that two separate integrations don't conflict with each other and update the Wiki on adding integrations.

**Comment by clptrsn** [comment]
Okay. Sounds good.

**Pull request merged**
