### PR TITLE
Added workast integration

### PR DESCRIPTION
**Pull request by rudivs**
- Toggl button appears in task lists
- Toggl button appears in subtasks
- Toggl button does not appear on lists of completed tasks
- Project is taken from the title of the list in which the task appears (this can be inconsistent between different organizing pages)

toggl_workast

image

### CODE REVIEW

**Comment by rudivs** [comment]
That's a great suggestion, @Phenome, that was bothering me too but I couldn't think of a good solution. I also added some extra functionality; this is a summary of the changes:

- Get project from dashboard if the name of the current list is 'Open tasks'
- If the project name is a Slack channel (starts with `#`), strip the `#`, replace `_` and `-` with spaces, and make it TitleCase
- Get tags from Workast, whether the task is minimized or open in task details view

**Comment by rudivs** [comment]
I just picked up a bug with the tags - any assignees are also picked up by the item-name selector. I'll see how I can make it more robust.

**Comment by rudivs** [comment]
Tested and should be working now. Also cleaned up how the sub-project (list header) is accessed, and explicitly checks that the task is not completed before adding the Toggl button. This also clears some JavaScript errors that I noticed from completed tasks having the subProject being null.

**Comment by Phenome** [comment]
Thanks, @rudivs ! It'll be available next release.

**Comment by rudivs** [comment]
Thanks for approving!

**Pull request merged**
