### PR TITLE
Added start and stop automatically settings as requested in issue #407

### PR DESCRIPTION
**Pull request by eatskolnikov**
Issue #407 
Added a "Start Automatically" option in settings.
If this option is checked and after opening the browser, the latest task will be started automatically.

Make sure the setting is checked
screen shot 2016-03-09 at 6 14 04 pm

Start tracking a task:
screen shot 2016-03-09 at 6 13 28 pm

Stop it:
screen shot 2016-03-09 at 6 13 37 pm

Close chrome:
screen shot 2016-03-09 at 6 14 38 pm

Open chrome:
screen shot 2016-03-09 at 6 15 00 pm

### CODE REVIEW

**Comment by eatskolnikov** [comment]
The stop automatically setting works like this:
Make sure the setting is checked
screen shot 2016-03-11 at 8 28 43 am

Start tracking:
screen shot 2016-03-11 at 8 29 03 am

Close the browser and open it again, the timer will be stopped
screen shot 2016-03-11 at 8 51 33 am

**Comment by IndrekV** [comment]
I've looked into this pull request and it seems that the stoping part does not work reliably. It works if you close window one by one, but does not work if you close browser with `cmd+Q`. This needs some more looking into before its ready to be merged.

Thank you for you work.

**Comment by eatskolnikov** [comment]
@IndrekV Thanks for the feedback and I'll look into it

**Comment by eatskolnikov** [comment]
@IndrekV sorry for the delay. I have a fun story about this issue. At first I was gonna use Chrome custom commands thing (https://developer.chrome.com/extensions/commands) but then ended up doing something just adding:
```js
window.onbeforeunload = function () {
  openWindowsCount = 0;
  TogglButton.stopTimeEntry(TogglButton.stopTrackingOnBrowserClosed);
};
```
This onbeforeunload function is only executed when chrome is completely closed, as is the case when the cmd+q shortcut is used.

**Comment by IndrekV** [comment]
I had to add some more functionality to make it work when browser started but all is good now. 

Thank you for your contribution.

**Pull request closed without merging**
