### PR TITLE
feat(focus): Add focus mode for pomodoro

### LINKED ISSUE #1567: [Phoenix] Add a clock view for running Pomodoro entry
- Make it optional
- Only render the current running entry in a circular countdown clock
- Add stop entry button

image

### PR DESCRIPTION
**Pull request by lise-toggl**
## :star2: What does this PR do?

Adds an optional focus mode while a pomodoro timer is running - shows a countdown timer instead of the usual entries list.

Current issues:
- The countdown doesn't update at the exact same time as the duration :(
- It works in the extension popup, but not when the popup is opened as a separate page

## :bug: Recommendations for testing

Turn the focus mode option on and start a timer.
Click on the countdown to stop it early.
Open the popup during a working 

## :memo: Links to relevant issues or information

Closes #1567

### CODE REVIEW

**Comment by shantanuraj** [comment]
Rebased changes on latest release branch

**Comment by lise-toggl** [comment]
Re: workaround if you think it's ok to not display the duration that sounds like a plan :)

If we invert the colours (like this idea) I think the cursor should change on the whole circle, and the whole circle should be clickable. What do you think?

**Comment by shantanuraj** [comment]
Didn't invert color, the big red-circle looked too jarring 

Fixed the problems stated in OP

Let's do a round of review to ensure

Focus mode only kicks in in pomdoro enabled and focus preference is turned on as well

**Comment by shantanuraj** [comment]
Didn't invert color, the big red-circle looked too jarring 

Fixed the problems stated in OP

Let's do a round of review to ensure

Focus mode only kicks in in pomdoro enabled and focus preference is turned on as well

**Comment by shantanuraj** [comment]
Didn't invert color, the big red-circle looked too jarring 

Fixed the problems stated in OP

Let's do a round of review to ensure

Focus mode only kicks in in pomdoro enabled and focus preference is turned on as well

**Comment by lise-toggl** [comment]
I found the duration fades each time you open the popup, is this intentional?
cut

Also, did you want to limit the cursor style and stop on click to the red rectangle only?

**Comment by shantanuraj** [comment]
@lise-toggl I've made some more improvements regarding the render
Extracted and refactored the timer code used in react components to hooks, scheduling next render using `requestAnimationFrame`. 
This is ready for review and hopefully merge now 🙇

**Comment by shantanuraj** [comment]
You can ignore changes made to `timerUtils.js` in 34ed96845313ef021a4008b55acf4b7849256d48
Just applied some lint fixes VS Code was complaining of

**Comment by lise-toggl** [comment]
very nice :clap:

**Pull request merged**
