### PR TITLE
Adding slack.com, dropbox.com, duolingo.com, W3Schools.com, Udemy.com, alza.cz, inbox.google.com, linustechtips.com, pc-help.cz support

### PR DESCRIPTION
**Pull request by DenisVCode**
Added Toggl button support for these websites:

- Slack.com

- Dropbox.com

- Duolingo.com

- W3Schools.com

- Udemy.com

- GoProForums.com

- PCPartPicker.com

- Developers.google.com

- Lego.com

- Nedatluj.cz

- Alza.cz

- Inbox.google.com

- LinusTechTips.com

- PC-HELP.cz

### CODE REVIEW

**Comment by IndrekV** [comment]
Just for information. The pull request will be evaluated and merged after the end of the toggl developer challenge (https://toggl.com/toggl-developer-challenge) on February 14th. Thank you for your contribution.

**Comment by IndrekV** [comment]
I've looked into your pull request and it seems that none of the integrations fetch the description and project name from the integrated tool's web page. This is the main purpose of adding the toggl button link to a web page. This pull request will not be merged in it's current state.

**Comment by DenisVCode** [comment]
@IndrekV Hello, I am sorry, I got it wrong. I will correct it until Sunday. Have a nice day.

**Comment by DenisVCode** [comment]
@IndrekV Hello, I hope it is ok now. If not, please let me know. Have a nice day.

**Comment by IndrekV** [comment]
I've decided not to merge this pull request.

Slack integration was added with #446
Google Inbox was added with #422

I think that the other tools introduced with the PR do not add enough of a value to the Toggl Button. The main aim of Toggl Button is to make it simple to track time with description and project that is taken from the integrated tool. These integrations do not represent that value and it would be easier to start the timer from Toggl Button dropdown and enter the data manually.

Thank you for taking the time to participate in our Toggl Developer Challenge.

**Pull request closed without merging**
