### PR TITLE
Fix xero button

### LINKED ISSUE #1059: Xero integration likely broken
Case 725662

A user is reporting that the button is shown behind the "files" icon in Xero on all screens and is not affected by resizing. 

image

### PR DESCRIPTION
**Pull request by ezaki**
Please remember the [Contributing Guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?

Xero changed UI.
This fixing show button in the list.

default

## :bug: Recommendations for testing

All changes should be tested across Chrome and Firefox.

## :memo: Links to relevant issues or information
Fixed #1059

### CODE REVIEW

**Comment by ezaki** [comment]
Thank you for your reply!

I'll try to fix for that pages.
please wait a moment.

**Comment by ezaki** [comment]
@tcrammond 
I fixed and push commit.
Check it, please.
If still not work, please tell me that page.

**Comment by tcrammond** [comment]
@ezaki looks good, thank you! Can you please remove all new `console.log()` and then we'll merge.

**Comment by ezaki** [comment]
It slipped my mind.
`console.log` removed!

**Pull request merged**
