### PR TITLE
Quire integration

### PR DESCRIPTION
**Pull request by RoryBarclay**
### Adds integration for quire.io

Adds a minimal toggl button inline to tasks displayed on Quire as requested in #1027, positioned to the left of the task item and existing controls.
As per the behavior of other inline controls, the toggl button is visible when the task is selected or hovered over.
The task tracked in toggl is the complete text of the task item in Quire.

image

- [X] Always run make lint and fix reported issues before submitting a pull request
- [X] Please use git squash and merge all your commits into one commit
- [X] Add description about the position of the button
- [X] Add screenshot of the working integration

### CODE REVIEW

**Comment by marcin-jaworski** [comment]
bump

**Comment by marcin-jaworski** [comment]
bump

**Comment by RoryBarclay** [comment]
Hey @tcrammond, looks like I failed badly at rebasing 🤔 
Lets abandon this PR for now and I'll re-implement this on a fresh fork when I get time.

**Comment by tcrammond** [comment]
Hey, we're cleaning up our backlog and since this PR has been inactive for a while, we're going to close it. Please feel free to revisit it some time, and we will review it again 🙇

**Comment by qins** [comment]
So wasted!

@RoryBarclay Any news? Quire is a nice service, what a pity there is no toggl support

**Pull request closed without merging**
