### PR TITLE
Add WorkFlowy integration.

### PR DESCRIPTION
**Pull request by ooblahman**
Creates minimal toggl button with workflowy node text as description beside each visible node.

Couldn't figure out how to easily distinguish the "header" workflowy nodes from the "body" ones. I think you have to filter further by class `.selected`, but I was unable to figure out how, so it looks a little ugly.

image

### CODE REVIEW

**Comment by ooblahman** [comment]
#753

**Comment by tcrammond** [comment]
Hi @ooblahman, thanks for the PR! I'll review it soon.

**Comment by ooblahman** [comment]
what is the status? @tcrammond

**Comment by tcrammond** [comment]
Hey @ooblahman 

A couple of us here use Workflowy and we thought it would be better if the toggl button was inside the context menu that appears when you hover over a bullet (this one):
screen shot 2017-02-10 at 16 48 10

This will look a lot cleaner. Do you think you can update your PR to do this?

FYI it's a bit of a pain to inspect that menu; I was able to trigger `mouseover` on a bullet in the console and then find it in the element tree though.

**Comment by bryanph** [comment]
Hey @ooblahman , we decided to clear up old PRs to make way for some big refactoring that is upcoming. If you wish to continue work on this PR please feel free to reopen. We will reconsider adding workflowy support in the future: see #533.

**Pull request closed without merging**
