### PR TITLE
Add HabitRPG integration

### PR DESCRIPTION
**Pull request by donbobka**
Pull request adds HabitRPG integration

### CODE REVIEW

**Comment by IndrekV** [comment]
Thank you for your contribution.

**Comment by Alys** [comment]
@donbobka Thank you on behalf of HabitRPG as well! We've already had one happy comment about it in the Tavern. :)

**Comment by Alys** [comment]
@donbobka In fact, I've checked with the HabitRPG staff and this can count towards a [contributor tier](http://habitrpg.wikia.com/wiki/Contributor_Rewards). Can you please give me your unique User ID (from Settings -> API)?

@IndrekV Sorry about hijacking your issue queue like this. I don't have any other way yet for contacting @donbobka.

**Comment by donbobka** [comment]
@Alys, wow. Thanks.
My user id: a9732680-8060-42e9-80f7-fd2309e69783

**Comment by Htarlov** [comment]
HabitRPG domain and name changed. It is now Habitica and habitica.com. So this integration doesn't work right now. Please someone change domain in script.

**Pull request merged**
