### PR TITLE
Added Service Now

### PR DESCRIPTION
**Pull request by FerventAnnotator**
Added entry for service now.
Added code for pulling service now info from page
Tickets or changes are the names for projects
Time entries tagged with the category, subcategory, incident and client

### CODE REVIEW

**Comment by FerventAnnotator** [comment]
Is there anything I need to change about this?

**Comment by effinofinus** [comment]
The functionality seems suitable, sensible fields are being collected from website. 

Although the "Business_Service" field would be more suitable for the project than "Number"

**Comment by FerventAnnotator** [comment]
The Incident or change number is the unique identifier for a specific piece of work and therefore better cover the general over a specific use case e.g. Company A doesn't use business service but everyone has a ticket number.  While it'd be nice to have Unique identifier that is separate from the project name the project names as it's not an available feature within the extension.  Additionally a number of companies that use service now will bill customers per ticket\change completed with the amount of time.  For those companies being able to state on a bill each discrete block of time spent on a ticket is quite valuable.  If you need a report with a breakdown of tasks the time entries get tagged with the priority, category and subcategory.

**Comment by LulzAugusto** [comment]
Can you give us instructions on how to sign up and get to the pages where the button should appear? Apparently, ServiceNow offers different services and they don't even have an easy to find sign up button on their home page. 😬

**Comment by bryanph** [comment]
Hi @FerventAnnotator, as @LulzAugusto noted we need a test account to test the integration and to assure that the integration works in the future. We are looking to do some refactoring work and improve the process for adding and maintaining integrations.

Are you still looking to work on this PR? If so, we'll need a few things:
* A test account for Service Now (preferably one we know is future proof so it doesn't get disabled).
* Some continuation work after reviews.

If not, could you also please let us know? This allows us to start the refactoring process earlier. Looking forward to your response.

**Comment by FerventAnnotator** [comment]
Hi,
When I get back to London I'll see if I can get a developer instance
running.

**Comment by tcrammond** [comment]
Hey, we're cleaning up our backlog and since this PR has been inactive for a while, we're going to close it. Please feel free to re-open when this is re-visited and we will review it again 🙇

**Pull request closed without merging**
