### PR TITLE
Added Evernote integration

### PR DESCRIPTION
**Pull request by schipa**
toggl-evernote

### CODE REVIEW

**Comment by IndrekV** [comment]
Just for information. The pull request will be evaluated and merged after the end of the toggl developer challenge (https://toggl.com/toggl-developer-challenge) on February 14th. Thank you for your contribution.

**Comment by IndrekV** [comment]
I'm not able to make this integration work. `The start timer links are not appearing for me`.

It also seems that you have done too much manual work with Mutation Observer instead of using the observer that is inside common.js

**Comment by schipa** [comment]
I fixed the selectors and the "Start timer" should appear.

The problem with the observer in `common.js` is that the dynamic loading of notes won't remove the `.toggl` class and thus prevents `renderTo` from calling the `renderer` function because `elems` will be empty.

**Comment by IndrekV** [comment]
Merged. I simplified the script and added project matching support. 

There is no need to remove and re-add the timer button. Using functions as `description` and `projectName` values, fetches the correct info when button is pressed.

Thank you for your contribution, sir!

**Pull request closed without merging**
