### PR TITLE
Add eventum support

### PR DESCRIPTION
**Pull request by glensc**
add support for [Eventum](https://launchpad.net/eventum) issue tracker.

as this particular issue tracker is not service, but you install it on your own, therefore added to `manifest.json` sample domain under [rfc2606](https://tools.ietf.org/html/rfc2606).

I wonder should this be somehow marked in README? the same problem exists for Trac based installations where you install Trac to your own infrastructure.

### CODE REVIEW

**Comment by glensc** [comment]
adding screenshot, so you can add it to [where can i find button?](https://github.com/toggl/toggl-button/wiki/Where-can-I-find-the-Button%3F) page after merging!

screenshot

**Comment by IndrekV** [comment]
This can not be merged at it's current state. There's no point in adding the example url to the manifest. Toggl Button does not support adding custom url-s that require global permissions and it is hard to add a correct url if this is mostly a self-hosted service. Maybe forking and creating your own version of Toggl Button is the way to go here.

**Comment by glensc** [comment]
how about adding all but manifest change? then the code is at least in one place.

**Comment by glensc** [comment]
Seems it is no longer possible to install custom built extensions on Windows, MacOSX will follow soon

https://support.google.com/chrome/answer/2811969

What is your suggestion how to still use toggl-button with custom domains?

**Comment by IndrekV** [comment]
Thank you for sharing. We'll look into the possibilities.

**Comment by glensc** [comment]
e0d7bb5befcddf12b7427ddacb40f121e6c9531f

**Comment by IndrekV** [comment]
We have decided not to change the permissions of Toggl Button, for users who need to use custom domains they can use the Developer mode and load extension from folder.

**Comment by glensc** [comment]
did you answer to this question?

> how about adding all but manifest change? then the code is at least in one place.

**Comment by IndrekV** [comment]
Yes I will add everything but the manifest.

**Comment by IndrekV** [comment]
Done.

**Comment by glensc** [comment]
thank you. however i need to make new PR as the code lived in fork for a while

**Comment by glensc** [comment]
f739fc123a3729bc21ad3d7845f829f5b77b1337

btw, you should had added `#207` in your commit message, then github would had autolinked the commit here.

**Pull request closed without merging**
