### PR TITLE
Update to Asana

### LINKED ISSUE #685: Disappearing button in Asana
> My toggl button within asana keeps disappearing the past few days since I've upgraded to the new interface (I'm not sure if this is related or not).
> I cleared all my cache, disabled the app and reauthorised access and when refreshing Asana the button reappeared on one task, but as soon as I navigate to another task it's disappeared again.
> Case #367261

### PR DESCRIPTION
**Pull request by hhermsen**
Fixes #685

### CODE REVIEW

**Comment by IndrekV** [comment]
I'm not sure what's it about but when I'm in asana there is no element named `.SingleTaskPane`.

**Comment by IndrekV** [comment]
I'm not sure what's it about but when I'm in asana there is no element named `.SingleTaskPane`.
The old integration worked for me. I have a free account in Asana and it's more than a year old. 

If you validate that the updated version works ok for you then we should just keep both.

**Comment by hhermsen** [comment]
If you create a new project, the layout code is different than before. Keeping both versions sounds good te me.

**Comment by IndrekV** [comment]
Thank you for your contribution, Sir.

**Pull request merged**
