### PR TITLE
fix: Workflowy styles

### PR DESCRIPTION
**Pull request by BeksOmega**
Please remember the [Contributing Guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?

Workflowy styles had gone a bit out of date. This fixes them! Original workflowy integration PR: #1335

Toggl1
Toggl2

## :bug: Recommendations for testing

Copied from the original PR

### Finding the Hover Button:
1. Navigated to [workflowy.com](https://workflowy.com/).
2. Created a bullet.
3. Hovered over the bullet (the circle part).
4. Observed how the toggl button appeared. (pass)

### Finding the More Options Button:
1. Navigated to [workflowy.com](https://workflowy.com/).
2. Created a bullet.
3. Clicked on the bullet (the circle part). This makes it so that that bullet is now the top bullet.
4. Clicked the more options menu on the right.
5. Observed how the toggl button appeared. (pass).

### And it Works in All the Styles
Toggl3
Toggl4

## :memo: Links to relevant issues or information

Original integration PR: #1335

### CODE REVIEW

**Comment by lise-toggl** [comment]
Hi @BeksOmega, thanks for the PR and sorry about the delay in getting back to you!

We tested your branch but couldn't get the Button to show up in either place. Could you confirm if it's still working on your side?

**Comment by BeksOmega** [comment]
Still working for me :/ Here were my steps for testing.

Chrome:
1. Completely removed the toggl-button from my chrome browser.
2. Confirmed that the button did not appear with the extension removed.
3. Ran npm start.
4. Loaded the unpacked extension.
5. Enabled all integrations.
6. Refreshed workflowy.
7. Confirmed that the button did appear.

Firefox:
1. Completley removed the toggl-button from my firefox browser.
2. COnfirmed that the button did not appear with the extension removed.
3. Ran npm start.
4. Loaded the temporary add on.
5. Enabled all integrations.
6. Refreshed workflowy.
7. Confirmed that the button did appear.

**Comment by lise-toggl** [comment]
Thanks for the detailed steps! I had a look into it and it looks like our DOM structure might be different, could we be on different versions of workflowy or something like that?

For example, on my side, `.flyout.menu` is not a direct descendant of `.name`:
image

**Comment by BeksOmega** [comment]
I think I figured out the problem! I had totally forgotten they added an option to open the menu via a button (I use the legacy hover option). It turns out that opening in that way does give you a different DOM structure. Thank you for finding that!

I tested it, and it should now be working :D

**Comment by lise-toggl** [comment]
Awesome, thanks for the update! :)

Everything is working great on my side now :+1:

**Pull request merged**
