### PR TITLE
add integration for ClickUp

### PR DESCRIPTION
**Pull request by sjsnider**
It wasn't made totally clear to me if you need to see a live version of the Toggl button in our app, if it is then just let me know and I can get you credentials to a staging site right away.

We are implementing Toggl in our task view.  The two screenshots show Toggl started and Toggl stopped.  Please let me know if you need anything else from me.  Would like to get this integration going ASAP.  Customers have been asking for it!

clickup toggl started

clickup toggl stopped

### CODE REVIEW

**Comment by sjsnider** [comment]
looking through other PRs it does look like you'd like to see it live, you can do so here, https://scott-dev-env.clickup.com/

email: sjsnider+toggl-test@gmail.com
pw: togglpass

logging in takes you to our list view, just click on the one task that shows up "Welcome to ClickUp" and you'll see the button in there.  First time a user hovers over the Toggl button it will prompt you to enter your Toggl api key to sync Toggl data with ClickUP.  I didn't hover over it with this account so you could see it.  Can also enter the api key in at any time in settings.  Totally optional to enter it in, feel free to just dismiss the modal.

Let me know if there's anything else I can provide.

**Comment by sjsnider** [comment]
@syko Just following up on this, still wanting to get this merged so our customers can use Toggl!

**Comment by sjsnider** [comment]
@tcrammond @Phenome @dooart @LulzAugusto  anyone there available to take a look at this or just provide a quick explanation why it appears no PRs are being reviewed?  Would be much appreciated

**Comment by langri-sha** [comment]
Hey @sjsnider, thanks for the PR 🙌! We're currently attending meetings and conferences and working through our backlog as fast as we can 🏃 💨 🔥 🔥 🔥, so sorry for keeping the PRs waiting. Hacktoberfest will be respected :)!

**Comment by sjsnider** [comment]
got it, thanks for the reply.  Please let me know when/if you're able to give us a time estimate on when you think you might get to it.

**Comment by Phenome** [comment]
Hey @sjsnider.
Again, thanks for the pr!
You're right about the behavior when creating new tags. Since we could also reproduce this on other integrations, it's a bug, and the fix is incoming.

About this integration, code looks good, so we're merging this. Sorry to take so long this time.

**Comment by sjsnider** [comment]
Sweet! Thanks!

I just removed the Toggl extension and then re-installed it, but I'm not seeing ClickUp in the list of apps to enable.  I assume there's some process you have to go through with Chrome now?

**Comment by Phenome** [comment]
Exactly. We do, yes.
But we'll probably go through some more open PRs so we can pack them with our next release. I'll get back to you once we do 🙂

**Comment by sjsnider** [comment]
Hey @Phenome any update on your guys' next release?

**Pull request merged**
