### PR TITLE
Pomodoro updates - #362

### PR DESCRIPTION
**Pull request by kretel**
Adding extra setting as per request  https://github.com/toggl/toggl-button/issues/362

- Add more settings. User can define if the timer stops when time ends or just notifies and keeps tracking.

### CODE REVIEW

**Comment by IndrekV** [comment]
I think the action buttons in the notification should also be different depending on the setting.

If timer is stopped it should be the same as right now:
- Continue latest
- Start new

If timer is not stopped by pomodoro:
- Stop
- Stop and start new

**Comment by kretel** [comment]
Agreed. Will apply the changes.

**Comment by eatskolnikov** [comment]
@kretel I took the liberty of fixing the conflict and added the buttons @IndrekV mentioned.
Here is the PR https://github.com/toggl/toggl-button/pull/514 (:

**Comment by kretel** [comment]
@eatskolnikov thank you for doing this. 

@IndrekV, do you think you can merge the PR #514 now ? 

Thanks,
Kris

**Pull request merged**
