### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by glensc**
keep the link clickable

### CODE REVIEW

**Comment by IndrekV** [comment]
Thank you for the contribution.

**Comment by IndrekV** [comment]
Actually I'll remove this all together as the Developer mode and loading unpacked extension should continue to work in the future. Just the packaged custom extensions will not be allowed anymore.

**Comment by glensc** [comment]
Do you have link with explanation that backs up your story?

**Comment by IndrekV** [comment]
The article on google talks only about packaged extensions. If unpacked extensions would be blocked it would not be possible to develop extensions so I think this will not happen.

**Pull request merged**
