### PR TITLE
fix(asana): Fix Asana detail view

### LINKED ISSUE #1631: Asana: new task view doesn't display Toggl button
### Environment details

* Operation system: Windows
* Extension version: 1.54.1

### Expected behavior
When I click on a task in a Saved Report, I get a "Task View" pane on the right side of the screen. In the past, at the top of the pane was a Toggl button. 

### Actual behavior
Asana has just redesigned the task view. It no longer displays a Toggl button. 

### Steps to reproduce the behavior
Open the task view in Asana for any task. Look for the Toggl button. 

### Additional details

* screenshots or screencapture
missing toggl button

### PR DESCRIPTION
**Pull request by lise-toggl**
## :star2: What does this PR do?

Fixes button not showing up on Asana's new detail view

## :bug: Recommendations for testing

Button should show up here and work as expected:
image

## :memo: Links to relevant issues or information

Closes #1631, #1633 and #1634

### CODE REVIEW

**Comment by rossgrambo** [comment]
I work over at Asana. Let me know if I can help get this merged! 😁

**Comment by shantanuraj** [comment]
@rossgrambo if you can verify if this branch works for you, it'll help us expedite the review process.

**Comment by rossgrambo** [comment]
This branch does not work for me, but I suspect it's because of user error, as I'm unfamiliar with anything but basic usage of toggl.

I have a toggl account and am logged in on chrome, and I'm not seeing buttons.

When debugging the extension on Asana, the last log file I see is `URL | domain-file: asana.js` and no button.
However, the same thing happens when I'm on github `URL | domain-file: github.js` and no button.

But when I'm at toggl.com, the logs continue with:
```
URL | domain-file: toggl.js
Load content script: [toggle.js]
Retrieved value sendUsageStatistics: true
```

Because it's happening to both github and asana, I assume it's something I'm missing.

**Comment by lise-toggl** [comment]
Hey @rossgrambo, thanks for giving it a try! Did you enable the integration inside Toggl Button settings?
image

**Comment by langri-sha** [comment]
Checked the board card and project task detail views, LGTM :+1:!

**Comment by rossgrambo** [comment]
Thanks @lise-toggl! That's what I was missing. It now works as expected! 😄

**Comment by lise-toggl** [comment]
@rossgrambo thanks for your help on this! :)

Would you be able to let us know if this new Asana detail view has been released to everyone? After releasing this change we've received a few reports of the button being gone, so I'm wondering if their detail view is different to the one we're seeing?

**Comment by rossgrambo** [comment]
@lise-toggl the new version is deployed to 50% of existing users and 100% of new users. 

Both versions will be around for another month or so. I suppose adding support for both might be the correct path forward. Sorry, I should have brought this up earlier!

**Comment by rossgrambo** [comment]
My coworkers said the 100% rollout is on Friday (Jan 10th). As long as things go according to plan, this new version of the toggl button should work on Friday. I'll keep you posted here if things change.

**Comment by lise-toggl** [comment]
Thanks, appreciate it :smile:

**Pull request merged**
