### PR TITLE
GitLab: Add GitLab labels as Toggl Tags

### PR DESCRIPTION
**Pull request by glensc**
Please remember the [Contributing Guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?

GitLab: Add GitLab labels as Toggl Tags. Requires GitLab 12.7

## :bug: Recommendations for testing

All changes should be tested across Chrome and Firefox.

## :memo: Links to relevant issues or information

- https://github.com/toggl/toggl-button/issues/1657

### CODE REVIEW

**Comment by glensc** [comment]
Seems there's bug in the toggl button core logic, my integration returns array of tags, but the toggl button code instead of checking multiple tags, concatenate them with comma.

I think it's the default behavior when an array is accessed as a string.

**Comment by glensc** [comment]
Looks like the schema expects tags to be string:
- https://github.com/toggl/toggl-button/blame/master/.github/CONTRIBUTING.md#L64-L74

however, at least the UI should be improved to explode tags by comma and select only tags that match.

**Comment by tcrammond** [comment]
Hey @glensc, I tried to test this but unfortunately I think things might have changed since you submitted the PR (it doesn't seem to work).

My issue UI doesn't have any `.qa-labels-block` in it, but it looks like my version of the Gitlab UI has `data-qa-selector="labels-block"` instead

FWIW this is what I see, with labels on the right:

Screenshot 2020-01-16 at 16 19 52

**Comment by glensc** [comment]
@tcrammond can you indicate gitlab version you're using or perhaps link to the test issue?

**Comment by tcrammond** [comment]
I'm not sure where to check the gitlab version, do you know where I can do that?

**Comment by glensc** [comment]
- https://es.lmgtfy.com/?q=gitlab+version
- https://stackoverflow.com/questions/21068773/how-to-check-the-version-of-gitlab
- https://gitlab.com/help

**Comment by glensc** [comment]
rebased query selector against gitlab 12.7

**Comment by glensc** [comment]
due toggl button not handling multiple tags properly, can't really understand what tags are selected like this:
- https://github.com/toggl/toggl-button/issues/1657#issuecomment-579688197

**Comment by glensc** [comment]
rebased after https://github.com/toggl/toggl-button/pull/1642

**Comment by glensc** [comment]
I'm not using this directly, I have added code top of this branch to customize GitLab labels -> Toggl Tags mapping.

So I'm not sure if this is usable on its own, i.e adding all labels as tags

**Comment by glensc** [comment]
For posterity the tag UI improvement issue is already created:
- https://github.com/toggl/toggl-button/issues/1657

**Pull request merged**
