### PR TITLE
feat(rebrand): Change theme colors

### PR DESCRIPTION
**Pull request by dpsxp**
## :star2: What does this PR do?
Change theme colors to match the new TogglTrack colors

## :bug: Recommendations for testing
- Check the colors, they should match our new design

### CODE REVIEW

**Review by Phenome — APPROVED** [review]
* Extension icon / settings page favicon ✔️ 
* Header and logo ✔️ 
* Sidebar and logo on settings page ✔️ 
* Icon embedded on pages ✔️ 
* `Done` button on start popup ✔️ 

Needed: popout link targetting the new URL.

Later: Reskin our checkboxes and switches from green to pink.

**Review by rylek90 — CHANGES_REQUESTED** [review]
Overall LGTM 🚀 

Button in popup appears red for me 
image

With running time entry button in navbar is grey 🤔 
image

**Comment by dpsxp** [comment]
@rylek90 I think you'll have to make a fresh install. I had the same problem locally.

**Comment by rylek90** [comment]
@dpsxp indeed! Sorry for messing around! 😅

**Review by rylek90 — APPROVED** [review]
me c colors! 🚀

**Comment by dpsxp** [comment]
No worries, I hope this a debug thing only tho 🙈

**Comment by rylek90** [comment]
> No worries, I hope this a debug thing only tho 🙈

🤞 

We can always add some notification to reinstall, we're good at it lately 😂

**Comment by louiskirsch** [comment]
Can you give us an option to change the color? I'm not a big fan of the pink theme.

**Comment by shantanuraj** [comment]
@louiskirsch I am sorry at the moment we don't have plans on supporting additional themes (other than light and dark)
I'll update this thread if we plan on adding more color-schemes

**Pull request merged**
