### PR TITLE
Added Zoho Boks Integration

### PR DESCRIPTION
**Pull request by JoshEpic**
Added Zoho Books integration

### CODE REVIEW

**Comment by IndrekV** [comment]
Just for information. The pull request will be evaluated and merged after the end of the toggl developer challenge (https://toggl.com/toggl-developer-challenge) on February 14th. Thank you for your contribution.

**Comment by IndrekV** [comment]
Could you please describe where the button is displayed in Zoho Books. A screenshot would also help.

**Comment by JoshEpic** [comment]
Hi,

Yes it is displayed when viewing an invoice or an estimate. 

Thank you,
Josh
toggle-button

**Comment by IndrekV** [comment]
Merged with rebase.

**Pull request closed without merging**
