### PR TITLE
feat: Add Dynamics 365 integration

### PR DESCRIPTION
**Pull request by DanielGoehler**
Please remember the [Contributing Guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?

Integration of Dynamics 365 Customer Engagement. It is visible on every entry when using the Unified Interface. On the Entry **Case** Case No. and Customer will be transferred to Toggle.

Screenshot

## :bug: Recommendations for testing

All changes should be tested across Chrome and Firefox.

## :memo: Links to relevant issues or information
#921 _Suggestion: Add to Case Page on Dynamics CRM/Dynamics 365_

### CODE REVIEW

**Comment by dooart** [comment]
Hey @DanielGoehler! Thank you for your contribution!

Your code seems alright, but I have no easy way to test your integration. I've requested a demo to Microsoft, but I'm afraid they'll not be very eager to help when I tell them the real reason I've applied for a demo. 😄 

Alternatively, what we could do is: I'll give you a list of test cases and you go through them to make sure everything is working and send me some screenshots. Would you be willing to do that?

Here's the list:
- Start the timer for case X and customer Y (please send a screenshot of the timer window correctly filled with case X as description and customer Y as project).
- After starting the timer, refresh the page to see if the timer button still appears as running (red icon).
- Click the Refresh button in the toolbar and see if there's still just one instance of the button on the page (a very common error is when dynamic changes to the page end up duplicating the button).

**Comment by DanielGoehler** [comment]
Hi @dooart,

I reached out via the Toggl Contact Form https://www.toggl.com/contact/. I hope my message reaches you.

Best regards,
  Daniel

**Comment by DanielGoehler** [comment]
Hi @dooart,
thanks for your feedback! I renamed the file and removed the project name, because you are right, this probably will not match and there is currently no field in "vanilla" Dynamics 365 Customer Engagement that relates to project name.

Best regards,
  Daniel

**Comment by oviliz** [comment]
@DanielGoehler is this still working for you with the latest M$ updates?

**Pull request merged**
