### PR TITLE
Integration/1117 new jira issue view

### PR DESCRIPTION
**Pull request by eLenoAr**
support for the new JIRA issue view added

### CODE REVIEW

**Comment by langri-sha** [comment]
Hey @eLenoAr! Could you please rebase on top of master and clear out the changes to the NPM lockfile?

Thanks for contributing :raised_hands:!

**Comment by eLenoAr** [comment]
@langri-sha done.
package-lock.json is reverted to master.

**Comment by AxaliaN** [comment]
Can this be merged? I have to switch to the old view constantly and this is just annoying... @eLenoAr thanks for the contribution :)

**Comment by m0n5t3r** [comment]
well, this version doesn't really work because the HTML in the new jira is terrible: classes are automatically generated and presumably change with every build (or at least change)

I got it working with more generic selectors (using the human-readable classes), at least for the issue view (views like the issue navigator thingy don't work yet)

pasting diff here, because I don't have any more time to fiddle with the thing right now:

```
diff --git a/src/scripts/content/atlassian.js b/src/scripts/content/atlassian.js
index 0cbaab9..ba0efae 100644
--- a/src/scripts/content/atlassian.js
+++ b/src/scripts/content/atlassian.js
@@ -63,11 +63,11 @@ togglbutton.render(
 
 // Jira 2018-09 new issue view
 togglbutton.render(
-  'div.sc-sdtwF:not(.toggl)',
+  '.new-issue-container object + div a:last-child:not(.toggl)',
   { observe: true },
   function(needle) {
-    var id = $('.sc-hUfwpO > span > span:last-child', needle),
-      description = $('.sc-ipqSdY h1:first-child'),
+    var id = $('span span', needle),
+      description = $('.new-issue-container h1:first-child'),
       container = createTag('div', 'jira-ghx-toggl-button'),
       link; 
 
@@ -78,7 +78,7 @@ togglbutton.render(
       });
 
       container.appendChild(link);
-      $('.sc-jMMfwr').appendChild(container);
+      needle.parentNode.appendChild(container);
     }
   }
 );

```

**Comment by tcrammond** [comment]
Hi, thanks for your efforts here. We're fixing issues with the Jira integration in an upcoming release, and have tried to account for the ever-changing Jira classes by using more generic and hopefully robust selectors.

I'll close this PR now and you can expect the new release to become available in the next few days as it rolls out to all users.

**Pull request closed without merging**
