### PR TITLE
feat(asana): Support new Asana UI (in beta)

### PR DESCRIPTION
**Pull request by nunofmn**
## :star2: What does this PR do?
- 0d9dc8b  - **feat(asana): Support new Asana UI (in beta)**

Spreadsheet view should be good (including clicking on a task in detail):

https://app.asana.com/0/729617904817453/list

Screenshot 2019-10-29 at 14 32 42

Older task lists should be good (including clicking on a task in detail):
https://app.asana.com/0/729616262525591/list

Screenshot 2019-10-29 at 14 33 10

## :bug: Recommendations for testing
 - Check if toggl button it's working correctly on the new Asana UI
- All changes should be tested across Chrome and Firefox.

## :memo: Links to relevant issues or information
Related #1508

### CODE REVIEW

**Comment by nunofmn** [comment]
Since we now have the new UI, I'm not sure if the button has a similar position and functionality as before. 🙈

**Comment by tcrammond** [comment]
@nunofmn Do you need someone else to take this one?

**Comment by tcrammond** [comment]
Picking this up

**Comment by tcrammond** [comment]
Updated, both current and beta list views should be decent. This integration needs to be updated to only show buttons on hover, but not doing that here right now.

**Pull request merged**
