### PR TITLE
Fixed button missing on Remember The Milk (RTM)

### PR DESCRIPTION
**Pull request by lunaticare**
Resolves issue #770

### CODE REVIEW

**Comment by lunaticare** [comment]
It now works
toggl-button rtm

**Comment by syko** [comment]
(sry, accidental close)

**Comment by leafi** [comment]
Not a fan of us having to repeatedly

Is it our policy to allow other types of selectors? (Surely we've done this before.) If so, how about...

Outermost: `div[class^='b-db-'][role='listbox'] [role='option']:not(.toggl)`
Description: `div[class^='b-db-'][role='listbox'] [role='option'] span[style*='user-select: text']`
Project: err dunno
Where to inject button: $(`the whole description selector`).filter(":parent") (yes, requires jQuery - for the parent part)

**Comment by leafi** [comment]
Could probably lose the 'b-db-' part for now, but only if they never do `role='listbox'` on something else.

**Comment by lunaticare** [comment]
@leafi fixed as you suggested, selector is more robust now.

**Comment by leafi** [comment]
Sorry, running a bit behind. Will look into this properly tomorrow & get it sorted. (I want to review against the batches of selectors used in the other content scripts, mull over the robustness of these selectors, and get something proper sorted for the project selector.)

**Pull request merged**
