### PR TITLE
added protonet integration

### PR DESCRIPTION
**Pull request by christianseel**
This PR adds a integration for protonet soul (https://protonet.info/)

The toggl button is added to each todo-detail-view next to the other options in the top right.

Integration screenshot:
voila_capture 2015-05-10_05-00-44_nachm

### CODE REVIEW

**Comment by IndrekV** [comment]
Is there a way to test it out with some demo account or something similar.

**Comment by christianseel** [comment]
Hi, actually this is not possible since a protonet server is a private server that companies can host from their offices. If you really need to test it, I could set up a test account on my server, but this one is on a custom domain so it's even more complicated.

**Comment by IndrekV** [comment]
Hi Christian,

As Protonet seems to be quite a custom solution, meaning that it is usually on a private server and on a custom domain, there is no generic url that Toggl Button can use.

**Comment by christianseel** [comment]
Hey, the avarage protonet user is always on `*.protonet.info`, which is the default subdomain for each protonet server.

**Pull request closed without merging**
