### PR TITLE
fix(todoist): get project name and label name

### LINKED ISSUE #1899: Projects and Tasks not being picked up in Todoist
* **OS version**:  11.0.1
* **Browser version**: Chrome 87
* **Extension version**: 1.67.1

#### Relevant integration (if any):

Todoist
### 🐛 Describe the bug

When in Todoist projects, and pressing button to start timer, it does not pick project or task from Track even if matching data exists. This works in "Today" view
### Expected behaviour

I'd expect project, and where applicable, task to be picked. 
### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to Todoist Projects
2. Make sure you have matching project/task in Track
3. Click button to start timer
4. It will not pick data

### Other details or context

[slack](https://toggl.slack.com/archives/C9LMUPD9T/p1608551860218200)

### PR DESCRIPTION
**Pull request by DesmondSylin**
Please remember the [Contributing Guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md) :heart:

## :star2: What does this PR do?
fixed get label name in all page and get project name in single project page

## :bug: Recommendations for testing

All changes should be tested across Chrome and Firefox.

## :memo: Links to relevant issues or information
Fixes #1899

### CODE REVIEW

**Review by rylek90 — APPROVED** [review]
LGTM :rocket:

**Review by rylek90 — CHANGES_REQUESTED** [review]
Thank you for contribution :raised_hands: 

Can you please fix commit message according to our [guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md#commit-message-format)?

**Comment by DesmondSylin** [comment]
> Thank you for contribution 🙌
> 
> Can you please fix commit message according to our [guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md#commit-message-format)?

ok, its done

**Review by dpsxp — APPROVED** [review]

**Comment by dpsxp** [comment]
Thanks @DesmondSylin for your contribution to this project. We really appreciate and we're sorry for taking so long to get this one merged. You should be able to see it in the next release 👍

**Pull request merged**
